/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface1.h"

bool_t
xdr_bloque (XDR *xdrs, bloque *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nombreArchivo, TAM_MAX_NOM_ARCHIVO))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datos.datos_val, (u_int *) &objp->datos.datos_len, TAM_MAX_BLOQUE_ARCHIVO))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dest_offset))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_cancion (XDR *xdrs, nodo_cancion *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->codigoCancion))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->titulo, TAM_MAX_NOM_ARCHIVO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tipo, TAM_MAX_NOM_ARCHIVO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->autor, TAM_MAX_NOM_ARCHIVO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->peso))
		 return FALSE;
	return TRUE;
}
