/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface3.h"

bool_t
xdr_datosCalculados (XDR *xdrs, datosCalculados *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->codigoCancion))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->titulo, TAM_MAX_NOM_ARCHIVO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tipo, TAM_MAX_NOM_ARCHIVO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->autor, TAM_MAX_NOM_ARCHIVO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->peso))
		 return FALSE;
	return TRUE;
}
