/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface2.h"

bool_t
xdr_bloque2 (XDR *xdrs, bloque2 *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nombreArchivo, TAM_MAX_NOM_ARCHIVO))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datos.datos_val, (u_int *) &objp->datos.datos_len, TAM_MAX_BLOQUE_ARCHIVO))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dest_offset))
		 return FALSE;
	return TRUE;
}
