/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface3.h"
int contadorMp3=0;
int contadorFLAC=0;
int  pesoTotal=0;

int *
enviar_notificacion_3_svc(datosCalculados *argp, struct svc_req *rqstp)
{
	static int  result;
	
	
	int aux=0;
	
	
	printf("\n\t\tNueva Notificación!!\n");
	printf("\n======= Una canción nueva se ha registrado =======");

	if(strcmp(argp->tipo,"mp3")==0){
		contadorMp3++;
	}else{
		contadorFLAC++;
	}
	
	pesoTotal=argp->peso+pesoTotal;

	printf("\nFecha y Hora de Registro: %s", argp->titulo);
	printf("\nCanciones mp3 registradas: %d", contadorMp3);
	printf("\nCanciones FLAC registradas: %d", contadorFLAC);
	printf("\nPeso en (Mb): %d", pesoTotal);
	printf("\n");
	result = 1;
	return &result;
}
