/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface1.h"
#include <stdbool.h>
#include "string.h"


int mostrarMenu();
void enviarArchivoAlServidor(char * nombreArchivo,CLIENT *clnt);
void IngresarDatosCancion(nodo_cancion * objCancion,char * nombreArchivo);
void consultaCancion(CLIENT *clnt);


void
programa_compartir_canciones_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char * nombreArchivo;
	int  *result_2;
	bloque  enviararchivo_1_arg;
	bool_t  *result_3;
	nodo_cancion objCancion;

	
	  
#ifndef	DEBUG
	clnt = clnt_create (host, programa_compartir_canciones, programa_compartir_canciones_version_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

int opcion;
	do{
		opcion=mostrarMenu();
		switch (opcion){
			case 1:
				
				nombreArchivo=(char*)malloc(20*sizeof(char));
				IngresarDatosCancion(&objCancion,nombreArchivo);
				
				
				//Registro de datos
				result_3 = registrarcancion_1(&objCancion, clnt);

				if (result_3 == (bool_t *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else if(*result_3==TRUE)
				{
					printf("\nCancion registrada exitosamente\n");
				}
				else{
					printf("\nError al registrar la cancion\n");
				}
				
			result_1 = creararchivo_1(&nombreArchivo, clnt);
			if (result_1 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			
			else{
				printf("\nArchivo vacio creado en el servidor");
				printf("\nProcedimiento a enviar en bloques el archivo");
				enviarArchivoAlServidor(nombreArchivo,clnt);
			}
				
				break;
			case 2:

			consultaCancion(clnt);
			

			case 3:
				exit(0);
			
		} 	
}while(opcion!=3);


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	programa_compartir_canciones_1 (host);
	
exit (0);
}

int mostrarMenu(){
int opcion=0;

		printf("-----------------------Menu-----------------------\n");
		printf("1.	Ingresar y enviar datos de una cancion\n");
		printf("2.	Consultar una cancion del servidor\n");
		printf("3.	Salir\n");
        printf("--------------------------------------------------");
		printf("\nDigite la opcion: \n");
		scanf("%d",&opcion);

return opcion;


}

void IngresarDatosCancion(nodo_cancion *objCancion,char * nombreArchivo){
	printf("\nDigite el id de la  cancion:\n ");
	scanf("%d",&objCancion->codigoCancion);
	printf("\nDigite el titulo de la  cancion: \n");
	scanf("%s",objCancion->titulo);
	printf("\nDigite el peso de la  cancion: \n");
	scanf("%d",&objCancion->peso);
	printf("\nDigite el nombre del Archivo \n");
	scanf("%s",nombreArchivo);
	
	do{
		printf("\nDigite el tipo de la  cancion: \n");
		scanf("%s",objCancion->tipo);
	}while(strcmp(objCancion->tipo,"mp3")!=0 && strcmp(objCancion->tipo,"FLAC")!=0 &&strcmp(objCancion->tipo,"flac")!=0);

	
	
}

void enviarArchivoAlServidor(char * nombreArchivo,CLIENT *clnt){
	//fopen abre el archivo
	//el arg r, permite abrir el archivo en modo lectura
	FILE *file;
	if(file=fopen(nombreArchivo,"r")){
		bool bandera=TRUE;
		int pos=0,cantidadBloques=0;
		bloque objBloque;
		objBloque.nombreArchivo=(char*)malloc(20*sizeof(char));
		strcpy(objBloque.nombreArchivo,nombreArchivo);
		objBloque.datos.datos_val=(char*)malloc(TAM_MAX_BLOQUE_ARCHIVO * sizeof(char));
		do{
			objBloque.datos.datos_len=fread(objBloque.datos.datos_val,1,TAM_MAX_BLOQUE_ARCHIVO,file);
			objBloque.dest_offset=pos;
			pos=pos+objBloque.datos.datos_len;
			int *resultado=enviararchivo_1(&objBloque,clnt);
			if(resultado==(int*) NULL){
				clnt_perror(clnt,"call failed");
				bandera=FALSE;
			}
			else{
				cantidadBloques++;
			}

		} while(objBloque.datos.datos_len==TAM_MAX_BLOQUE_ARCHIVO);
		free(objBloque.datos.datos_val);
		fclose(file);
		if(bandera==TRUE){
			printf("\ncancion enviada exitosamente a partir de %d bloques\n",cantidadBloques);

		}else{
			printf("\nError al enviar la cancion");
		}
	}else{
		printf("\nEl archivo no existe\n");
		exit(1);
	}
}

void consultaCancion(CLIENT *clnt){
	char * nombreCancion;
	nodo_cancion *result_4;
	memset(result_4, 0, 0);
	nombreCancion = (char*)malloc(30*sizeof(char));
	printf("\nIngrese el titulo de la canción a buscar: ");
	scanf("%s", nombreCancion);
	result_4 = consultarcancion_1(&nombreCancion, clnt);
	if (result_4 == (nodo_cancion *)NULL) {
		clnt_perror(clnt, "call failed");
	}else if (result_4->codigoCancion > 0) {
		printf("\nCanción encontrada");
		printf("\nId canción: %d", result_4->codigoCancion);
		printf("\nNombre canción: %s", result_4->titulo);
		printf("\nTipo canción: %s", result_4->tipo);
		printf("\nPeso canción: %d mb\n", (*result_4).peso);
	} else {
		printf("\nLo sentimos.\n la canción %s no existe!\n", nombreCancion);
	}
}